//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblEmployee()
        {
            this.TblInfoes = new HashSet<TblInfo>();
        }
    
        public int EmpId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public int DegId { get; set; }
        public string EmployeeContactNo { get; set; }
        public System.DateTime MakeDate { get; set; }
        public string Password { get; set; }
    
        public virtual TblDesignation TblDesignation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblInfo> TblInfoes { get; set; }
    }
}
