//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticalTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblInfo
    {
        public int Id { get; set; }
        public int DesigId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime MakeDate { get; set; }
    
        public virtual TblDesignation TblDesignation { get; set; }
        public virtual TblEmployee TblEmployee { get; set; }
    }
}
